FROM centos:7
MAINTAINER "475402366@qq.com"  
RUN yum install -y mysql-server mysql  
RUN systemctl start mysqld &&\  
    mysql -e "grant all privileges on *.* to 'root'@'%' identified by '123456' WITH GRANT OPTION ;"&&\  
    mysql -e "grant all privileges on *.* to 'root'@'localhost' identified by '123456' WITH GRANT OPTION ;"&&\ 
    mysql -u root -p123456 -e "show databases;"  
EXPOSE 3306
CMD ["/usr/sbin/init"]